### ISSUE TITLE
Change Hall No. to a dropdown list

### ISSUE THREAD

**Issue by JayjeetAtGithub** [lugnitdgp/jcc-registration-portal#23]
Change Hall No. from textbox to a dropdown list containg items Hall 1 , Hall 2 , Hall 3 , Hall 7, Hall 11 , Hall 13 , Hall 14 , Hall 6

**Comment by rapperdinesh** [comment]
Hi I am working on this issue.

**Comment by JayjeetAtGithub** [comment]
Sure ! Go Ahead :)
