### ISSUE TITLE
Remove hardcoding of static assets from the templates

### ISSUE THREAD

**Issue by JayjeetAtGithub** [lugnitdgp/jcc-registration-portal#4]
Currently the url of static assets are hardcoded which is not a good practice. Replace with `{% static '/path/to/asset.jpg' %}` wherever the url of static asset is hardcoded

**Comment by JayjeetAtGithub** [comment]
@rapperdinesh  Are you working on this issue ?

**Comment by rapperdinesh** [comment]
it will take a some time as it involves Django(learning currently). I am catching up tutorials(about "views" and other libraries+syntax). But I will complete it soon.

**Comment by rapperdinesh** [comment]
yes working on it....

**Comment by rapperdinesh** [comment]
Made a PR on this issue. plz review it
