### ISSUE TITLE
Fix the admin panel url

### ISSUE THREAD

**Issue by JayjeetAtGithub** [lugnitdgp/jcc-registration-portal#9]
Going to `localhost:8000/admin` doesn't redirect to admin site but `localhost:8000/admin/` does . This should be corrected.

**Comment by rapperdinesh** [comment]
Hey @JayjeetAtGithub I sent a PR on this issue. Just a small change("/") and this bug is resolved.

**Comment by rapperdinesh** [comment]
We can add one more line in urls.py to make both URL redirect to admin panel

**Comment by JayjeetAtGithub** [comment]
@rapperdinesh Adding two lines one with only `admin` and other with `admin/` will throw warnings ! So i think removing `/` is ok for now
